go-vela/worker

cmd/server/operate.go, executor/executor.go, executor/linux/build.go, executor/linux/build_test.go, executor/linux/service.go, executor/linux/stage.go, executor/linux/stage_test.go, executor/linux/step.go
The GolangCI check is failing because of the linter checks.
[I went through and fixed](https://github.com/go-vela/worker/pull/66/commits/ce597fe814bc1a05acb7a5ad1d3bc32d22d20f8c) **most of the issues**, but it's still complaining about the length of our function for only one (`PlanBuild`).
https://golangci.com/r/github.com/go-vela/worker/pulls/66
I'd vote we skip the linter failure and not worry about it 👍
=> feat(executor): add functions to stream logs

cmd/vela-worker/run.go
This prevents a `panic` when we attempt to create a new `executor` and add it to our collection of executors.
The code that does this can be found here:
https://github.com/go-vela/worker/blob/6bf556146feec9c8869a17faef914ae4888ef99b/cmd/vela-worker/operate.go#L55-L65
We store a collection of executors so we can query the builds being ran and kill them if need be 👍
=> fix: explictly make executor map

cmd/vela-worker/operate.go
We are currently violating a [CommonMistake](https://github.com/golang/go/wiki/CommonMistakes#using-goroutines-on-loop-iterator-variables) in Go.
Currently the index of each executor is equal to `w.Config.Build.Limit` because the loop completes before the routines start.
=> fix: capture executor index before creating routine

cmd/vela-worker/run.go, go.mod, go.sum
See https://github.com/go-vela/pkg-executor/pull/46 and https://github.com/go-vela/pkg-runtime/pull/52 for more details
=> chore: update go-vela dependencies for host volumes

docker-compose.yml
Adding hostnames to worker containers in docker-compose to allow the server to address the worker api locally.
=> chore: set hostname in docker-compose

cmd/vela-worker/flags.go, cmd/vela-worker/run.go, cmd/vela-worker/server.go, cmd/vela-worker/worker.go
Allows (optionally) setting a certificate which is then used in [RunTLS](https://pkg.go.dev/github.com/gin-gonic/gin?tab=doc#Engine.RunTLS)
If certs are not provided, the functionality stays the same as the current state.
=> feat: allow server to run with TLS

cmd/vela-worker/flags.go, cmd/vela-worker/run.go, cmd/vela-worker/server.go, cmd/vela-worker/worker.go
Removes the ability to run with TLS.
Will re-add after release of 0.6.0.
=> fix: revert PR 113

.github/workflows/prerelease.yml, .github/workflows/publish.yml, Dockerfile-alpine
Adding another `Dockerfile` based on alpine since I unfortunately need access to some image with a shell to allow me to modify the environment variables before the binary is started. My specific use case involves needing to generate the VELA_QUEUE_CONFIG` environment variable utilizing others that are injected at run time.
- Add `Dockerfile-alpine` file to utilize alpine as base image instead of scratch
- Update `.github/workflows/publish.yml` to publish `latest-alpine` image
- Update `.github/workflows/prerelease.yml` to publish `${GITHUB_TAG}-latest` image
=> chore(docker): publish alpine images

.env.example, .gitignore, DOCS.md, docker-compose.yml
Closes https://github.com/go-vela/community/issues/150
Related to https://github.com/go-vela/ui/pull/232
Updates all references to `secrets.env` to now be `.env` to remain consistent with [go-vela/ui](https://github.com/go-vela/ui)
=> refactor: secrets.env -> .env for consistency

cmd/vela-worker/run.go, go.mod, go.sum
Adding the `runtime.allowed-privileged-images` flag from https://github.com/go-vela/pkg-runtime/pull/62.
=> feat: add allow list for privileged containers

cmd/vela-worker/operate.go, go.mod, go.sum
Update the worker to send the `build_limit` value to the server during the specified check-in interval. Depends on https://github.com/go-vela/types/pull/121 and https://github.com/go-vela/server/pull/219 being merged.
closes: https://github.com/go-vela/community/issues/164
=> enhance(workers): track build_limit on server

cmd/vela-worker/register.go
Removing a check that isn't currently checking anything. If we remove this check the error is still caught below. Currently this is causing an issue when attempting to add a worker that doesn't yet exist in the db.
=> fix: remove nil check from worker registration

cmd/vela-worker/operate.go, cmd/vela-worker/register.go
mades the registration process a little more readable and allows the worker to retry registering if the worker was not previously registered. This removes a race condition where the server must be available before the worker
fixes https://github.com/go-vela/community/issues/185
=> fix: allow workers to retry registering with the server

docker-compose.yml
I was attempting to test some changes locally in the [go-vela/pkg-executor](https://github.com/go-vela/pkg-executor) codebase.
When I attempted to run a `make up` in this repo and login to the UI on http://localhost:8888 it wouldn't work.
After looking at the compose setup in [go-vela/server](https://github.com/go-vela/server) I realized that we changed the `VELA_WEBUI_ADDR` variable.
It appears we modified this variable in https://github.com/go-vela/server/pull/241 and never made the same change here.
=> fix: web UI address for server in docker-compose

cmd/vela-worker/exec.go, go.mod, go.sum
Part of the effort for https://github.com/go-vela/community/issues/54
Based off of https://github.com/go-vela/pkg-executor/pull/110
This will set the version information for the executor which is used in logs and environment variables.
=> feat: add version information to executor

.github/CONTRIBUTING.md, .golangci.yml, api/executor.go, api/health.go, api/metrics.go, cmd/vela-worker/exec.go, cmd/vela-worker/register.go, cmd/vela-worker/run.go, cmd/vela-worker/start.go, cmd/vela-worker/worker.go, router/build.go, router/executor.go, router/middleware/executor/executor.go, router/middleware/header.go, router/middleware/logger_test.go, router/middleware/payload.go, router/middleware/perm/doc.go, router/middleware/perm/perm.go, router/middleware/token/doc.go, router/middleware/token/token.go, router/middleware/user/doc.go, router/middleware/user/user.go, router/pipeline.go, router/repo.go
Continuation of the efforts from https://github.com/go-vela/mock/pull/76 and https://github.com/go-vela/types/pull/122
* Updating the contributing guide to include fixing linter warnings if any are present
* Skipping the `dupl` and `lll` linters on `*_test.go` files
* Added `nolint` directives across the repo to address any current linter issues
=> chore: linter setup and fixes, doc changes

api/build.go
Returns the build struct instead of a string saying "canceled build X" so the api has more context of the build canceled.
=> fix(cancel): return build struct instead of string resp

go.mod, go.sum
Related to https://github.com/go-vela/pkg-executor/pull/151 and https://github.com/go-vela/pkg-runtime/pull/114
This pulls in the latest changes for the [go-vela/pkg-executor](https://github.com/go-vela/pkg-executor) and [go-vela/pkg-runtime](https://github.com/go-vela/pkg-runtime) codebases.
The primary focus is to address the bug resolved with https://github.com/go-vela/pkg-runtime/pull/114.
=> chore: upgrade go-vela/pkg-executor on latest

go.mod, go.sum
Related to https://github.com/go-vela/pkg-executor/pull/152 and https://github.com/go-vela/pkg-runtime/pull/115.
This is a backport of https://github.com/go-vela/pkg-runtime/pull/114 for the `v0.7.x` release.
This pulls in the `v0.7.5` tag for the [go-vela/pkg-executor](https://github.com/go-vela/pkg-executor) codebase.
=> chore: upgrade go-vela/pkg-executor on v0.7.5

go.mod, go.sum
Dependency updates needed for https://github.com/go-vela/types/pull/175
=> chore: update dependencies for types pr 175

docker-compose.yml
Related to https://github.com/go-vela/server/pull/418
This fixes the database configuration variables for the `server` service in the Docker compose file.
=> fix(compose): database config for server

cmd/vela-worker/main.go
This updates the `github.com/go-vela/worker` app to output the version information to stdout on startup:
```sh
$ docker logs worker
{
"canonical": "v0.8.1",
"major": 0,
"minor": 8,
"patch": 1,
"metadata": {
"architecture": "amd64",
"build_date": "2021-06-15T08:43:01Z",
"compiler": "gc",
"git_commit": "2685530895be807f8bccf675c478618ade728192",
"go_version": "go1.16.5",
"operating_system": "linux"
}
}
{"code":"https://github.com/go-vela/worker/","docs":"https://go-vela.github.io/docs/concepts/infrastructure/worker/","level":"info","msg":"Vela Worker","registry":"https://hub.docker.com/r/target/vela-worker/","time":"2021-06-15T13:43:42Z"}
<more logs>
```
=> feat: output version info to stdout

executor/linux/service.go, executor/linux/step.go
fixes a bug in the linux executor where timed chunks are not written until the buffer becomes larger than the size of the log itself.
=> fix: compare time chunks against zero

.env.example, DOCS.md, docker-compose.yml
Related to https://github.com/go-vela/server/pull/536
This updates any references of `SOURCE_*` -> `SCM_*` based off the above change.
=> fix: local setup with server

runtime/docker/image.go
Based off of https://github.com/go-vela/worker/pull/246
An issue was discovered with the `target/vela-worker:latest` Docker image produced from this codebase.
We pulled that version into our lower environments today for testing and noticed a discrepancy:
The issue seems specifically isolated to when the worker attempts to pull Docker images.
SEE EDIT - ~Thus far, was unsuccessful in reproducing locally but it could be related to us using an internal registry mirror.~ 
At any rate, was able to reproduce the issue on our internal infrastructure and this seems to resolve that issue.
Thanks to [a comment made](https://github.com/go-vela/worker/pull/253#issuecomment-995163389) by @wass3r, I was able to figure out how to reproduce it locally.
[In the above …
=> fix(docker): pulling images without output

.github/workflows/build.yml, .github/workflows/prerelease.yml, .github/workflows/publish.yml, .github/workflows/release.yml, .github/workflows/reviewdog.yml, .github/workflows/test.yml, .github/workflows/validate.yml, go.mod
Updates Go to 1.17, GitHub Actions pipelines included.
xref: go-vela/types#221
=> chore(deps): update go to 1.17

executor/linux/step.go, executor/linux/step_test.go
When pulling secret values to be masked, we need to catch the instance where a secret is not allowed for that event. Otherwise, when the map does not find the secret, it returns an empty string.
=> fix(step): add catch block for disallowed secrets

executor/linux/step.go, executor/linux/step_test.go
Backport for patch release (v0.12.1). 
When users inject secrets for a container that are not allowed for the event or simply do not exist, the `getSecretValues` function would set them to an empty string, resulting in ugly logs. 
Earlier, merged PR: https://github.com/go-vela/worker/pull/272
=> fix(logs/secrets): check for disallowed/non-existent secrets

executor/linux/build.go, executor/linux/stage.go, executor/local/build.go, executor/local/stage.go
`Pulling` is a Docker-specific term that does not apply to the Kubernetes runtime. `Preparing` is more generic and can apply to both. So, replace `Pulling` with `Preparing` in the logs.
=> refactor(logs): Replace "Pulling" with "Preparing" in init step logs

runtime/kubernetes/container.go, runtime/kubernetes/container_test.go, runtime/kubernetes/kubernetes_test.go
This primarily moves the Kubernetes Client + Watch mocking logic into a reusable function so that any other (future) methods that need to issue a watch in the k8s API can easily do so in tests.
In the actual code, I have a couple of minor watch-related refactoring commits as well:
- Rename watch->podWatch for clarity
- Close the podWatch in WaitContainer
- Escape selector just in case
=> refactor(kubernetes): Refactor watch related code

runtime/docker/opts_test.go, runtime/kubernetes/opts_test.go
Quick PR to increase test coverage
=> chore: Add tests for runtime WithLogger opt

executor/context_test.go, mock/docker/docker.go, runtime/context_test.go
These are already silenced in several other places. So, let's get reviewdog full-review to stop complaining.
🎉 This makes reviewdog / full-revew green!
Replaces #305 where I accidentally had my commit on master (which I then reset to upstream/master). Doh.
=> refactor: silence lint issues

runtime/kubernetes/build.go
A `\n` was missing from the init logs, causing this:
```
> Inspecting pod for pipeline org-repo-32metadata:
creationTimestamp: null
name: org-repo-32
spec:
...
```
So, this adds the missing newline.
=> bugfix(k8s): add newline to init step output

runtime/kubernetes/container.go
go-vela/pkg-runtime#151 was ineffective (did not improve things) and caused a lot of errors in the logs:
```
{"build":...,"executor":"linux","host":"...",
"level":"error",
"msg":"previous terminated container \"...\" in pod \"...\" not found",
"repo":"...","runtime":"kubernetes","time":"2022-04-14T18:58:36Z","user":"...","version":"..."}
```
Another user also reported this issue in slack, and I confirmed.
https://gophers.slack.com/archives/CNRRKE8KY/p1646859613212159?thread_ts=1646859573.285529&cid=CNRRKE8KY
=> revert(k8s): Revert go-vela/pkg-runtime#151

runtime/kubernetes/container.go, runtime/kubernetes/container_test.go, runtime/kubernetes/image.go
Closes https://github.com/go-vela/community/issues/564
slightly refactors the test so that I could include a failing test case.
=> bugfix(k8s): avoid InspectContainer panic where container is not Terminated

runtime/context_test.go, runtime/docker/build_test.go, runtime/docker/container_test.go, runtime/docker/docker_test.go, runtime/docker/image_test.go, runtime/docker/network_test.go, runtime/docker/opts_test.go, runtime/docker/volume_test.go, runtime/kubernetes/build_test.go, runtime/kubernetes/container_test.go, runtime/kubernetes/image_test.go, runtime/kubernetes/kubernetes_test.go, runtime/kubernetes/network_test.go, runtime/kubernetes/opts_test.go, runtime/kubernetes/volume_test.go, runtime/runtime_test.go, runtime/setup_test.go
I use Goland to run `go test`. At least with Goland, `testing.Run()` improves the output and test selection. And it makes it easier to see which subtest has failed.
As I develop and refactor, I would really like to see this everywhere. This starts with all tests under `runtime/`.
After this is merged I can prepare another one that does `executor/`.
=> tests: Convert runtime tests to subtests

cmd/vela-worker/exec.go
The duplicate DestroyBuild call causes a bunch of errors in the log about the build already being destroyed.
So, let's just drop the duplicate call.
Extracted from #304 so it can be reviewed separately.
Fixes https://github.com/go-vela/community/issues/204
=> refactor: drop duplicate executor.DestroyBuild call

runtime/kubernetes/build_test.go, runtime/kubernetes/container.go, runtime/kubernetes/container_test.go, runtime/kubernetes/image.go, runtime/kubernetes/kubernetes.go
A bug report in slack pointed out that with services the kubernetes Runtime sometimes gets the wrong container.
See: https://gophers.slack.com/archives/CNRRKE8KY/p1646859800708539?thread_ts=1646859573.285529&cid=CNRRKE8KY
> I am also seeing a crash when adding services to the pipeline, panic: runtime error: index out of range [-1].  It looks like the logic https://github.com/go-vela/worker/blob/7c9599fdd5b4cb9d26ff235d41479cfe56f4f3ba/runtime/kubernetes/image.go#L55-L57 to exclude the init isn’t holding true on my deployment when using services.
So, this replaces magic index calculation with an index lookup map.
=> bugfix(k8s): avoid "index out of range" panic by replacing magic indexes with containerLookup map

runtime/kubernetes/build.go, runtime/kubernetes/container.go
The API calls in the kubernetes runtime all use `context.Background()`. They should use the passed context instead.
Extracted from #304 so it can be reviewed separately.
=> refactor: cleanup context passing in kubernetes runtime

executor/context_test.go, executor/executor_test.go, executor/linux/api_test.go, executor/linux/build_test.go, executor/linux/linux_test.go, executor/linux/opts_test.go, executor/linux/secret_test.go, executor/linux/service_test.go, executor/linux/stage_test.go, executor/linux/step_test.go, executor/local/api_test.go, executor/local/build_test.go, executor/local/local_test.go, executor/local/opts_test.go, executor/local/service_test.go, executor/local/stage_test.go, executor/local/step_test.go, executor/setup_test.go
I use Goland to run `go test`. At least with Goland, `testing.Run()` improves the output and test selection. And it makes it easier to see which subtest has failed.
As I develop and refactor, I would really like to see this everywhere. This updates all tests under `executor/` as #312 did for `runtime/`.
=> tests: Convert executor tests to subtests

internal/build/snapshot_test.go, internal/build/upload_test.go, internal/image/image_test.go, internal/service/environment_test.go, internal/service/load_test.go, internal/service/snapshot_test.go, internal/service/upload_test.go, internal/step/environment_test.go, internal/step/load_test.go, internal/step/skip_test.go, internal/step/snapshot_test.go, internal/step/upload_test.go, internal/volume/volume_test.go
I use Goland to run `go test`. At least with Goland, `testing.Run()` improves the output and test selection. And it makes it easier to see which subtest has failed.
As I develop and refactor, I would really like to see this everywhere. This converts all tests under `internal/` like #312 did for `runtime/`.
=> tests: Convert internal/ tests to subtests

.github/workflows/reviewdog.yml
It was installing 1.18 which can panic or have a variety of silent failures.
See: https://github.com/reviewdog/action-golangci-lint/issues/249
Here is an example silent failures:
- 1.18 was installed: https://github.com/go-vela/worker/runs/6098658651?check_suite_focus=true#step:4:18
- failed: https://github.com/go-vela/worker/runs/6098658651?check_suite_focus=true#step:4:84
```
/__w/_temp/reviewdog-F3Z0zl/golangci-lint-1.45.2-linux-amd64/golangci-lint run --out-format line-number --config=.golangci.yml
level=error msg="Timeout exceeded: try increasing it by passing --timeout option"
/__w/_temp/reviewdog-F3Z0zl/reviewdog -f=golangci-lint -name=golangci -reporter=github-pr-review -filter-mode=diff_context -fail-on-error=true -level=error
```
The reviewdog action always installs go, so using …
=> fix(ci): Fix silent failures in GHA reviewdog workflow

runtime/kubernetes/container.go, runtime/kubernetes/container_test.go, runtime/kubernetes/kubernetes_test.go
Follow up for #308 which successfully prevented a panic, but was still logging errors (about the pause image running) when it shouldn't have. It seems the test case added in #308 did not cover the pause image running, so this adds a couple of tests for that to ensure that that does NOT fail.
We have to use the canonical (parsed) pause image or it won't match at runtime:
https://github.com/go-vela/worker/blob/c25339835ea70c10e00d947ab3c08e2ab31b2135/runtime/kubernetes/container.go#L138
I also check for the simple non-canonical image name as well to simplify any unrelated tests that might incidentally use this.
~Also add a helpful note/comment about ContainerState objects.~
=> bugfix(k8s): do not log false-positive error when pause image is running

runtime/kubernetes/container.go
While implementing #304 (improving context usage) and then #317 (improve worker log context management) I noticed that the Kubernetes Runtime's `TailContainer` ignores the context as it makes its requests. This fixes that so that tailing will stop if the streamCtx (which gets passed to TailContainer) is canceled.
=> bugfix: make sure kubernetes log streaming gets canceled with build

cmd/vela-worker/exec.go, cmd/vela-worker/operate.go
Closes https://github.com/go-vela/community/issues/562
~Pass the context along in the executor. The `buildCtx` is derived from the global ctx (`gctx`) so that signal-based worker shutdown trickles down to the `buildCtx` as well (see [cmd/vela-worker/start.go](https://github.com/go-vela/worker/blob/master/cmd/vela-worker/start.go#L27-L53)).~
I documented why we do not pass the executor context and derive the `buildCtx` from it.
Since there are several contexts in the `exec()` function, I renamed `ctx` to `timeoutCtx` to clarify which context is getting passed to each method.
=> refactor(executor): clarify why use different contexts

executor/linux/build.go, executor/local/build.go, runtime/kubernetes/container.go
Partially reverts #329 (see https://github.com/go-vela/worker/pull/329#discussion_r869658946).
In juggling all of my PRs, I thought I tested them merged together, but somehow I missed the breakage this caused.
We expect (at least part of) logsFunc to continue running after TailContainer returns.
Then StreamStep/StreamService/etc read from the returned ReadCloser until the end of the stream.
So, if the context gets canceled at the end of TailContainer (as introduced in #329), then the streaming is stopped before `Stream*` has read anything from it. So, log capture in the kubernetes runtime is currently broken for v0.14 😢 .
This fixes it by not creating+cancelling a new context in kubernetes TailContainer.
Also, I added/improved a log message about streaming output in each of the linux and …
=> bugfix(k8s): Drop TailContainer's logsContext to avoid early cancel

codecov.yml, runtime/kubernetes/kubernetes.go, runtime/kubernetes/mock.go
I will be adding several other mock utilities in future PRs to facilitate executor tests that use the kubernetes runtime. As these are meant for use in other packages, I have to export them, but I want to make it very very obvious that these should only be used in tests, not production code.
So, I think it makes sense to move all those utilities, including `NewMock` into a new `mock.go` file.
For a preview of the utilities in this file, check out the executor-k8s-tests branch:
https://github.com/go-vela/worker/blob/executor-k8s-tests/runtime/kubernetes/mock.go
=> refactor: move kubernetes runtime mock code to separate file

executor/linux/build_test.go, executor/linux/opts_test.go, executor/linux/secret_test.go, executor/linux/service_test.go, executor/linux/stage_test.go, executor/linux/step_test.go
@JordanSussman, @jbrockopp and I worked on adding executor tests that use the kubernetes runtime. You can see the results of that effort in the [executor-k8s-tests](https://github.com/go-vela/worker/compare/executor-k8s-tests) branch. This PR prepares for getting all of those test cases added. This PR:
- renames var: `_runtime` to `_docker` (plus a few other related var renames)
- Adds `runtime` arg (to be accessed as `test.runtime`)
- In some tests, pass in the runtime itself in `test.runtime`.
- In other tests, pass a constant because the runtime will need to be recreated for every test.
- resorted some of the imports
=> refactor(executor tests): Make runtime a test arg

executor/linux/build_test.go
@JordanSussman, @jbrockopp and I worked on adding executor tests that use the kubernetes runtime. You can see the results of that effort in the [executor-k8s-tests](https://github.com/go-vela/worker/compare/executor-k8s-tests) branch. This PR prepares for getting all of those test cases added. This PR:
- sorts the imports in `executor/linux/build_test.go`
- adjusts tests in `executor/linux/build_test.go` to check for logging un/expected errors. This is needed because logs are the only way to know if some areas of the code get hit, and because the logging happens in a goroutine, so we need to check the behavior of that goroutine when the function under test is doing its thing.
=> enhance(executor tests): test StreamBuild logging during build tests

executor/linux/api_test.go, executor/linux/build_test.go, executor/linux/driver_test.go, executor/linux/linux_test.go, executor/linux/opts_test.go, executor/linux/secret_test.go
@JordanSussman, @jbrockopp and I worked on adding executor tests that use the kubernetes runtime. You can see the results of that effort in the [executor-k8s-tests](https://github.com/go-vela/worker/compare/executor-k8s-tests) branch. This PR prepares for getting all of those test cases added. This PR:
- modify the `testSteps` test helper to accept a runtime argument
- calls `pipeline.Sanitize(runtime)` in the `testSteps` helper to sanitize container/build names for the given runtime
- calls `pipeline.Sanitize(runtime)` in tests as well, where required
This was a smaller PR, so I also included:
- enhance: update error message that was missing a test.name
- chore: sorts some imports
=> enhance(executor tests): Sanitize pipelines to handle runtime specific differences

executor/linux/build_test.go, executor/linux/secret_test.go, runtime/kubernetes/mock.go, runtime/kubernetes/pod_tracker.go
@JordanSussman, @jbrockopp and I worked on adding executor tests that use the kubernetes runtime. You can see the results of that effort in the [executor-k8s-tests](https://github.com/go-vela/worker/compare/executor-k8s-tests) branch. This PR prepares for getting all of those test cases added. I plan to add the test cases separately once more of the changes needed to manage the k8s mocks are included in the executor tests.
The Kubernetes runtime normally does some setup during AssembleBuild: We pre-populate the cache of the Mock PodTracker which watches the k8s API for changes to the pod (where build:pod maps 1:1). In any tests that call CreateBuild, we need to trigger that setup for the Mock after CreateBuild is called. So, we export a new `SetupMock` function that the executor tests can …
=> enhance(executor tests): Call k8s SetupMock method after CreateBuild in tests

executor/linux/build_test.go, executor/linux/secret_test.go, executor/linux/stage_test.go
could be merged at any time since it's backwards compatible. tests won't break until  https://github.com/go-vela/server/pull/755 is merged and worker depends on the updated package. this PR should fix the test breakage.
=> fix(tests): accommodate clone image change in server

executor/linux/build_test.go, executor/linux/secret_test.go, runtime/kubernetes/build.go, runtime/kubernetes/mock.go
@JordanSussman, @jbrockopp and I worked on adding executor tests that use the kubernetes runtime. You can see the results of that effort in the [executor-k8s-tests](https://github.com/go-vela/worker/compare/executor-k8s-tests) branch. This PR prepares for getting all of those test cases added. I plan to add the test cases separately once more of the changes needed to manage the k8s mocks are included in the executor tests.
This PR adds another part of the k8s mock management logic. In order to make the mocks during the ExecBuild test, we need 2 more exported methods in the kubernetes runtime:
- `StartPodTracker`
- `SimulateStatusUpdate`
K8s runtime tests have to manage starting the PodTracker which subscribes to a stream is k8s events. That is not part of the runtime interface, however, …
=> enhance(executor tests): Manage k8s mocks for Executor exec tests

executor/linux/build_test.go, runtime/kubernetes/kubernetes.go, runtime/kubernetes/mock.go
@JordanSussman, @jbrockopp and I worked on adding executor tests that use the kubernetes runtime. You can see the results of that effort in the [executor-k8s-tests](https://github.com/go-vela/worker/compare/executor-k8s-tests) branch. This PR prepares for getting all of those test cases added. I plan to add the test cases separately in a few PRs after this PR is merged.
This PR adds another part of the k8s mock management logic. In order to make the mocks during the AssembleBui9ld test, we need 2 more exported methods in the kubernetes runtime:
- `WaitForPodTrackerReady`
- `WaitForPodCreate`
K8s runtime tests have to wait for certain events (esp `<-c.PodTracker.Ready`) before adjusting the k8s mock at the appropriate points. The things needed to do that are not part of the runtime …
=> enhance(executor tests):  Manage k8s mocks for Executor AssembleBuild test

api/register.go, mock/worker/register.go, mock/worker/server.go
- adds mock for /register
- fixes return code when no token was passed (4xx instead of 5xx)
=> feat(mock): add support for register endpoint

cmd/vela-worker/exec.go, cmd/vela-worker/operate.go, cmd/vela-worker/run.go
just adding more logging around registration. also changed some casing to be more consistent with the other logs (lower-case).
=> enhance: operate/exec logging

cmd/vela-worker/operate.go
the inner `err` might not return an error, ie. it will be `nil`, but is overwriting the outer `err`
=> fix: err shadowing

api/register.go, cmd/vela-worker/server.go, go.mod, router/middleware/worker.go, router/middleware/worker_test.go
this stuffs the worker hostname into the gin context which is used as a simple pre-validation that the incoming registration token is valid for the host. it improves the registration experience.
currently, if you supply a wrong hostname, the validation fails on the server AFTER successfully passing through the /register endpoint on the worker. as an admin, it looks like registration was successful when in fact, the worker is in a failing check in loop. this change should prevent that scenario.
=> fix(register): verify hostname

cmd/vela-worker/exec.go, go.mod, go.sum
Part of https://github.com/go-vela/community/issues/811
Depends on https://github.com/go-vela/types/pull/292
This should allow the worker to invalidate stale queued builds. A stale build is a build that was queued before a Vela upgrade or downgrade if the two Vela versions do not share the same queue ItemVersion.
In the future, we could do something even nicer and ask the server to recompile and requeue the build.
Closes https://github.com/go-vela/community/issues/811
=> feat!: Use queue Item.ItemVersion field to fail stale builds

executor/linux/build.go, executor/linux/secret.go, executor/linux/service.go, executor/linux/step.go, go.mod, go.sum, internal/step/snapshot.go
Ref: https://github.com/go-vela/server/pull/879 and https://github.com/go-vela/sdk-go/pull/242
No longer returning the log with update calls, so we can remove that extra `_log` assignment at a few points in the code base. Max log size will be checked using the in-memory value of `_log` rather than what is returned from the server. Provided the call was successful, it should be the exact same value.
=> enhance(log): no library log return for update calls

docker-compose.yml
[Deprecation notice](https://hub.docker.com/_/vault)
=> fix(compose): use hashicorp/vault docker repo

cmd/vela-worker/exec.go
`w.VelaClient` does not have the right auth scopes for updating a build, but the `execBuildClient` does.
=> fix(exec): use exec client when updating build after failed item version check

executor/linux/build.go
Closes https://github.com/go-vela/community/issues/125.
While we can leverage the hover display on the build nav bar to check the worker that ran a specific build, I've found this to be a bit finicky and more difficult to analyze older builds. Throwing some basic worker / runtime info in the init step seems like a fairly simple win. 
I can also foresee this change being temporary if/when [the init step overhaul proposal](https://github.com/go-vela/community/pull/789) gets off the ground and running.
=> enhance(init): display basic worker info in init step logs

cmd/vela-worker/exec.go, cmd/vela-worker/operate.go, cmd/vela-worker/run.go, cmd/vela-worker/validate.go, docker-compose.yml, executor/linux/secret_test.go, go.mod, go.sum
Changes:
- Use velaClient to request GetInfo for queue credentials
Depends on [server #957](https://github.com/go-vela/server/pull/957)
=> feat(queue): use GetInfo for setup

cmd/vela-worker/exec.go, cmd/vela-worker/operate.go
this should make it nicer for admins in the instance there is a temporary issue on the queue availability. previously, this could cause the worker to become unregistered resulting in admin work. this change will not error the worker (and cause it to restart). it will log the error and wait for the configured queue timeout before continuing business as usual.
=> fix(queue): avoid worker restart on queue fail

executor/linux/build.go, executor/linux/stage.go, executor/local/build.go, executor/local/stage.go, go.mod, go.sum, internal/step/skip.go, internal/step/skip_test.go
From https://github.com/go-vela/types/pull/327 and https://github.com/go-vela/server/pull/985
Issue: https://github.com/go-vela/community/issues/435
=> fix(skip): surface error when failing to determine whether a container should execute

cmd/vela-worker/operate.go, cmd/vela-worker/register.go, cmd/vela-worker/worker.go, docker-compose.yml, go.mod, go.sum
Changes:
- Utilize ping function from Server to check queue connection and set status appropriately. 
- Depends on [Server 991](https://github.com/go-vela/server/pull/991)
=> fix(status): properly reflect worker status in db

cmd/vela-worker/exec.go, executor/linux/build.go
When the `VELA_EXECUTOR_ENFORCE_TRUSTED_REPOS` has been enabled, and an untrusted repo has been denied a build, the resulting error is
`error:build denied, repo must be trusted in order to run privileged images`
It would be convenient if the error specified which image is privileged.
The changes in this PR capture the last privileged image and returns that in the error message.
=> feat: specify which privileged image is being pulled for denied build

cmd/vela-worker/exec.go
it was populating the field with build numbers which are not as useful ;)
=> fix: use build id to populate RunningBuildIDs

executor/linux/build.go, executor/linux/service.go
missing some newline escapes for services + lazy secrets
> thought: should we move this into `injectSecrets` ?
=> fix: escape newline secrets before injection

executor/linux/build.go, executor/linux/build_test.go, executor/linux/service.go, executor/linux/step.go, executor/linux/testdata/build/steps/basic_secrets.yml
this isolates operations for lazy loaded secrets and makes sure the secrets go through the same process as regular secrets. the current implementation had the potential to inadvertently result in unexpected secret values (even for regular secrets), in particular for multiline secrets and/or secrets with escaped newlines.
this also moves the `escapeNewlineSecrets()` on `c.Secrets` to be called once, instead of for however many steps (and services) a pipeline had. it was calling it over and over for the same secrets. this is not necessary for this fix, it's just excessive. if there's concern, i'm happy to remove from this PR.
=> fix(secrets): isolate lazy secret loading

cmd/vela-worker/operate.go, cmd/vela-worker/run.go, docker-compose.yml
Closes https://github.com/go-vela/community/issues/876
Added address to `docker-compose.yml` with a note about what happens when it's not there.
=> enhance(queue): support worker-sourced queue address if given

executor/linux/build.go, executor/linux/stage.go, executor/local/build.go, executor/local/stage.go
Add an informational log prior to each download/use of an image during the initialization step of a build for visibility. 
https://github.com/go-vela/community/issues/915
=> enhance(logging): add info log prior to each download/use of an image during init step

cmd/vela-worker/exec.go, cmd/vela-worker/register.go
Similar to our server compilation retry loop, we can avoid killing the worker on failed server communications by adding the same logic. These failings come from network blips and timeouts mainly, and simply pausing should give the worker another chance at processing the build. This will limit "dropped" builds, and — if the admins choose worker registration — unregistered workers.
Example pipeline:
```yaml
steps:
- name: sleep
image: alpine:latest
commands:
- sleep 30
- name: goodbye
image: alpine:latest
commands:
- echo "goodbye"
```
Testing process (shell):
```sh
$ make up
...
...
$ docker kill server
$ docker restart server
```
The above will result in a complete loss of the build if the registration process is not enabled OR an unregistered worker if the registration process is …
=> enhance: retry build processing on failed server comms

executor/linux/opts.go, executor/linux/outputs.go, runtime/kubernetes/container.go
Some follow up from https://github.com/go-vela/worker/pull/591
=> chore(outputs): update comments

cmd/vela-worker/operate.go
If the worker has no build running, terminating the worker should be far more responsive than letting the check in interval expire. This change introduces a 5 second ticker that checks if the context is done or if the interval has been reached for check in.
=> enhance(operate): check in loop more responsive to termination signal

executor/linux/build.go, executor/linux/stage.go
This will help prevent accidental leakage of the netrc password used in builds
=> fix(stream): add netrc password to mask targets

cmd/vela-worker/register.go
closes https://github.com/go-vela/community/issues/1016
since check-in can (and does) happen while processing builds, status is getting set to the wrong value. the fix uses the helper function to determine the proper status.
=> fix(status): set correct status after checkin

cmd/vela-worker/exec.go, docker-compose.yml
This fixes an error where all executors try to share the outputs container config of whichever exec process last set it.
I'm also increasing the local stack build limit to 3 because this will help prevent future issues like this without sacrificing any sort of convenience for developers.
=> fix(exec): dereference outputs container config for executor setup

cmd/vela-worker/register.go
Applying https://github.com/go-vela/worker/pull/611 to `v0.25.2` patch release
=> fix(patch/v25.2): apply worker status fix

cmd/vela-worker/exec.go
Applying https://github.com/go-vela/worker/pull/612 to patch `v0.25.2`
=> fix(patch/v25.2): dereference outputs ctn config

executor/linux/build.go, executor/linux/secret.go, executor/linux/secret_test.go
We've added a couple features to the worker (OIDC and Outputs), yet we didn't update the secret container config to account for these. 
These are both very important when considering masked outputs and Vault OIDC policies.
=> fix(secret): update env values for secret origin ctn

executor/local/build.go, executor/local/build_test.go, executor/local/local.go, executor/local/opts.go, executor/local/outputs.go, executor/local/outputs_test.go, executor/local/stage.go, executor/local/stage_test.go, executor/local/step.go, executor/setup.go
Updating local exec capabilities
=> fix: update local executor code to include outputs

cmd/vela-worker/client.go, cmd/vela-worker/exec.go, go.mod, go.sum
Follow up from https://github.com/go-vela/server/pull/1337 and https://github.com/go-vela/sdk-go/pull/369
=> enhance(client): use scm token as secondary auth header for exec client
